apiVersion: cert-manager.io/v1
kind: ClusterIssuer
spec:
  acme:
    server: {{ .Values.clusterissuer.server }}
    email: {{ .Values.clusterissuer.email }}
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class: nginx
